version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: nest-app-container
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    env_file: .env
    command: sh -c "npm run start:dev & sleep 20 && npm run seed"
    working_dir: /usr/src/app
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    external: true 